import { defineStore } from 'pinia'
import { ref, computed } from 'vue'

export interface MenuItem {
  id: number
  name: string
  description: string
  price: number
  originalPrice?: number
  category: 'Hot Coffee' | 'Cold Coffee' | 'Specialty' | 'Food' | 'Sweets & Cakes'
  scentType: string        // reused as "flavour profile"
  stock: number
  lowStockThreshold: number
  gradient: string
  accent: string
  image: string
  rating: number
  reviews: number
  featured?: boolean
  isNew?: boolean
}

export const useProductsStore = defineStore('products', () => {
  const products = ref<MenuItem[]>([
    { id: 1,  name: 'Espresso',           description: 'Pure and intense. A double shot of premium single-origin espresso, crafted for those who love bold, concentrated flavour.',                                     price: 3.50,                category: 'Hot Coffee',  scentType: 'Bold & Intense',    stock: 80,  lowStockThreshold: 20, gradient: 'linear-gradient(145deg,#2c1008,#4a1e0a)', accent: '#c8813a', image: 'https://images.unsplash.com/photo-1596952954288-16862b37b44b?w=600&fit=crop&auto=format&q=85', rating: 4.9, reviews: 2134, featured: true },
    { id: 2,  name: 'Cappuccino',         description: 'Balanced and velvety. Equal parts espresso, steamed milk, and rich foam — a classic Italian favourite done to perfection.',                                   price: 4.50,                category: 'Hot Coffee',  scentType: 'Rich & Creamy',     stock: 65,  lowStockThreshold: 15, gradient: 'linear-gradient(145deg,#7c3a1e,#c87941)', accent: '#f0c27f', image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?w=600&fit=crop&auto=format&q=85', rating: 4.8, reviews: 1876, featured: true },
    { id: 3,  name: 'Caffe Latte',        description: 'Smooth and comforting. A generous pour of steamed milk over a double espresso base, with just a touch of delicate foam on top.',                             price: 4.75,                category: 'Hot Coffee',  scentType: 'Smooth & Milky',    stock: 70,  lowStockThreshold: 15, gradient: 'linear-gradient(145deg,#c8956c,#f5e6d3)', accent: '#8B4513', image: 'https://images.unsplash.com/photo-1570968915860-54d5d301fa13?w=600&fit=crop&auto=format&q=85', rating: 4.7, reviews: 2567, featured: true },
    { id: 4,  name: 'Americano',          description: 'Clean and bold. Espresso shots pulled long with hot water — a straightforward cup that highlights the depth of our coffee beans.',                            price: 3.75,                category: 'Hot Coffee',  scentType: 'Clean & Bold',      stock: 90,  lowStockThreshold: 20, gradient: 'linear-gradient(145deg,#1a0a04,#3d1c08)', accent: '#d4a060', image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&fit=crop&auto=format&q=85', rating: 4.6, reviews: 987  },
    { id: 5,  name: 'Cold Brew',          description: 'Steeped for 18 hours. Our cold brew is smooth, naturally sweet, and low in acidity — served over ice for the perfect slow coffee experience.',               price: 5.00,                category: 'Cold Coffee', scentType: 'Smooth & Sweet',    stock: 40,  lowStockThreshold: 10, gradient: 'linear-gradient(145deg,#0d0704,#2c1810)', accent: '#a0522d', image: 'https://images.unsplash.com/photo-1517959105821-eae173431639?w=600&fit=crop&auto=format&q=85', rating: 4.8, reviews: 1432 },
    { id: 6,  name: 'Caramel Macchiato', description: 'Layers of indulgence. Vanilla-infused milk topped with espresso and a golden caramel drizzle — sweet, strong, and utterly satisfying.',                      price: 5.50, originalPrice: 6.50, category: 'Specialty', scentType: 'Sweet & Caramel', stock: 35,  lowStockThreshold: 10, gradient: 'linear-gradient(145deg,#f0a940,#c8813a)', accent: '#8B4513', image: 'https://images.unsplash.com/photo-1485808191679-5f86510bd3e0?w=600&fit=crop&auto=format&q=85', rating: 4.9, reviews: 3241, isNew: false },
    { id: 7,  name: 'Mocha',             description: 'Coffee meets chocolate. Rich espresso blended with dark chocolate sauce and steamed milk, crowned with a cloud of whipped cream.',                             price: 5.25,                category: 'Hot Coffee',  scentType: 'Chocolatey',        stock: 50,  lowStockThreshold: 12, gradient: 'linear-gradient(145deg,#3d1c08,#6b3a2a)', accent: '#d4a060', image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=600&fit=crop&auto=format&q=85', rating: 4.7, reviews: 1654 },
    { id: 8,  name: 'Flat White',        description: 'Espresso forward. A ristretto-based drink with velvety microfoam milk — stronger than a latte, smoother than a cappuccino.',                                  price: 4.50,                category: 'Hot Coffee',  scentType: 'Velvety & Strong',  stock: 60,  lowStockThreshold: 15, gradient: 'linear-gradient(145deg,#fdf6ec,#f5e6d3)', accent: '#8B4513', image: 'https://images.unsplash.com/photo-1527018601521-77acd16e2b15?w=600&fit=crop&auto=format&q=85', rating: 4.6, reviews: 876  },
    { id: 9,  name: 'Iced Latte',        description: 'Cool and refreshing. A double espresso poured over fresh ice and cold milk — the perfect pick-me-up on a warm day.',                                          price: 5.00,                category: 'Cold Coffee', scentType: 'Refreshing & Cool', stock: 55,  lowStockThreshold: 12, gradient: 'linear-gradient(145deg,#dbeafe,#bfdbfe)', accent: '#6b3a2a', image: 'https://images.unsplash.com/photo-1497636577773-f1231844b336?w=600&fit=crop&auto=format&q=85', rating: 4.7, reviews: 2098, isNew: true },
    { id: 10, name: 'Matcha Latte',      description: 'Earthy and vibrant. Premium ceremonial-grade matcha whisked smooth with oat milk — an energising alternative with a natural green glow.',                    price: 5.25,                category: 'Specialty',   scentType: 'Earthy & Vibrant',  stock: 28,  lowStockThreshold: 8,  gradient: 'linear-gradient(145deg,#d1fae5,#6ee7b7)', accent: '#065f46', image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&fit=crop&auto=format&q=85', rating: 4.5, reviews: 1120, isNew: true },
    { id: 11, name: 'Vanilla Latte',     description: 'Warm and fragrant. Silky steamed milk, house-made vanilla syrup, and a rich espresso base — comfort in every sip.',                                           price: 5.00,                category: 'Hot Coffee',  scentType: 'Warm & Fragrant',   stock: 45,  lowStockThreshold: 10, gradient: 'linear-gradient(145deg,#fef3c7,#fde68a)', accent: '#92400e', image: 'https://images.unsplash.com/photo-1572715376701-98568319fd0b?w=600&fit=crop&auto=format&q=85', rating: 4.7, reviews: 1789 },
    { id: 12, name: 'Cortado',           description: 'Equal and balanced. A small but mighty equal-parts espresso and steamed milk — no foam, no fuss. Just pure coffee harmony.',                                  price: 4.00,                category: 'Hot Coffee',  scentType: 'Balanced & Pure',   stock: 30,  lowStockThreshold: 8,  gradient: 'linear-gradient(145deg,#78350f,#d97706)',  accent: '#fbbf24', image: 'https://images.unsplash.com/photo-1513530534585-c7b1394c6d51?w=600&fit=crop&auto=format&q=85', rating: 4.8, reviews: 765  },

    // ── Sweets & Cakes — London UK Favourites (no alcohol) ─────────────────
    { id: 13, name: 'Classic Scone',            description: 'A warm, golden British scone served with velvety clotted cream and rich strawberry jam — the crown jewel of London afternoon tea.',                                                                       price: 3.50,                category: 'Sweets & Cakes', scentType: 'Buttery & Classic',      stock: 30,  lowStockThreshold: 8,  gradient: 'linear-gradient(145deg,#fef3c7,#fde68a)',   accent: '#d4a040', image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&fit=crop&auto=format&q=85', rating: 4.8, reviews: 892,  isNew: true },
    { id: 14, name: 'Victoria Sponge',          description: 'Britain\'s most beloved cake. Two light golden sponge layers filled with fresh cream and raspberry jam, finished with a dusting of icing sugar.',                                                         price: 4.50,                category: 'Sweets & Cakes', scentType: 'Light & Airy',           stock: 20,  lowStockThreshold: 6,  gradient: 'linear-gradient(145deg,#fef9c3,#fde68a)',   accent: '#f5c200', image: 'https://images.unsplash.com/photo-1464349095431-e9a21285b19c?w=600&fit=crop&auto=format&q=85', rating: 4.9, reviews: 1240 },
    { id: 15, name: 'Lemon Drizzle Cake',       description: 'Zesty and irresistible. A moist almond sponge drenched in sharp lemon glaze — the UK\'s most ordered café cake, beloved slice after slice.',                                                             price: 4.00,                category: 'Sweets & Cakes', scentType: 'Citrusy & Bright',       stock: 18,  lowStockThreshold: 5,  gradient: 'linear-gradient(145deg,#fef9c3,#fde047)',   accent: '#f5c200', image: 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=600&fit=crop&auto=format&q=85', rating: 4.8, reviews: 2103, featured: true },
    { id: 16, name: 'Carrot Cake',              description: 'Warmly spiced with cinnamon and nutmeg, packed with fresh carrot and walnuts, crowned with a thick layer of smooth cream cheese frosting.',                                                               price: 4.50,                category: 'Sweets & Cakes', scentType: 'Spiced & Wholesome',     stock: 15,  lowStockThreshold: 5,  gradient: 'linear-gradient(145deg,#fde68a,#f59e0b)',   accent: '#d97706', image: 'https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=600&fit=crop&auto=format&q=85', rating: 4.7, reviews: 876  },
    { id: 17, name: 'Chocolate Brownie',        description: 'Dense, fudgy, and intensely chocolatey. Crisp crackle on top, gooey in the middle — a London café staple that never goes out of style.',                                                                 price: 3.75,                category: 'Sweets & Cakes', scentType: 'Fudgy & Rich',           stock: 25,  lowStockThreshold: 8,  gradient: 'linear-gradient(145deg,#3d1c08,#6b3a2a)',   accent: '#d4a060', image: 'https://images.unsplash.com/photo-1606313564200-e75d5e3d7343?w=600&fit=crop&auto=format&q=85', rating: 4.9, reviews: 3421 },
    { id: 18, name: "Millionaire's Shortbread", description: 'Three layers of pure indulgence: crumbly Scottish shortbread, thick salted caramel, and a dark chocolate top with a white chocolate drizzle.',                                                           price: 3.50,                category: 'Sweets & Cakes', scentType: 'Caramel & Shortbread',   stock: 22,  lowStockThreshold: 6,  gradient: 'linear-gradient(145deg,#f0a820,#c07810)',   accent: '#f5c200', image: 'https://images.unsplash.com/photo-1558326567-98ae2405596b?w=600&fit=crop&auto=format&q=85', rating: 4.9, reviews: 1876 },
    { id: 19, name: 'Biscoff Cheesecake',       description: 'The UK\'s most talked-about café dessert. Creamy no-bake cheesecake on a Lotus biscuit base, topped with silky Biscoff spread and a whole cookie.',                                                      price: 5.50,                category: 'Sweets & Cakes', scentType: 'Creamy & Caramelised',   stock: 12,  lowStockThreshold: 4,  gradient: 'linear-gradient(145deg,#d4841c,#8b5e3c)',   accent: '#d4841c', image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600&fit=crop&auto=format&q=85', rating: 5.0, reviews: 4102, isNew: true },
    { id: 20, name: 'Cinnamon Roll',            description: 'Freshly baked daily. Soft and pillowy with layers of warm cinnamon sugar, finished with a generous drizzle of vanilla cream cheese icing.',                                                               price: 4.00,                category: 'Sweets & Cakes', scentType: 'Warm & Spiced',          stock: 18,  lowStockThreshold: 5,  gradient: 'linear-gradient(145deg,#fde68a,#d4a040)',   accent: '#d4a040', image: 'https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=600&fit=crop&auto=format&q=85', rating: 4.8, reviews: 1543, featured: true },
    { id: 21, name: 'Sticky Toffee Pudding',    description: 'Warm dense date sponge drenched in rich, buttery toffee sauce — Britain\'s ultimate comfort dessert, served warm and heavenly.',                                                                           price: 5.00,                category: 'Sweets & Cakes', scentType: 'Warm & Toffee',          stock: 14,  lowStockThreshold: 4,  gradient: 'linear-gradient(145deg,#3d1c08,#78350f)',   accent: '#f0a820', image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&fit=crop&auto=format&q=85', rating: 4.9, reviews: 2876 },
    { id: 22, name: 'Banoffee Pie',             description: 'A British invention loved worldwide. Buttery biscuit base, thick dulce de leche, fresh banana slices and a generous cloud of softly whipped cream.',                                                       price: 5.00,                category: 'Sweets & Cakes', scentType: 'Banana & Toffee',        stock: 12,  lowStockThreshold: 4,  gradient: 'linear-gradient(145deg,#fef3c7,#fde68a)',   accent: '#f5c200', image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&fit=crop&auto=format&q=85', rating: 4.8, reviews: 1654 },
    { id: 23, name: 'Eton Mess',                description: 'A glorious British mess of crushed meringue, fresh strawberries and softly whipped cream — light, fruity and perfectly indulgent.',                                                                        price: 4.50,                category: 'Sweets & Cakes', scentType: 'Fresh & Fruity',         stock: 10,  lowStockThreshold: 3,  gradient: 'linear-gradient(145deg,#fce7f3,#fbcfe8)',   accent: '#ec4899', image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&fit=crop&auto=format&q=85', rating: 4.7, reviews: 987,  isNew: true },
    { id: 24, name: 'Jam Doughnut',             description: 'A British bakery icon. Pillowy soft dough fried golden, rolled in caster sugar and bursting with sweet strawberry jam — a timeless treat.',                                                                price: 2.75,                category: 'Sweets & Cakes', scentType: 'Sweet & Pillowy',        stock: 35,  lowStockThreshold: 10, gradient: 'linear-gradient(145deg,#fde68a,#f59e0b)',   accent: '#dc2626', image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&fit=crop&auto=format&q=85', rating: 4.6, reviews: 3102 },
    { id: 25, name: 'Chocolate Éclair',         description: 'Elegant choux pastry piped with Chantilly cream and topped with a glossy dark chocolate glaze — a French-British café favourite.',                                                                         price: 4.00,                category: 'Sweets & Cakes', scentType: 'Elegant & Chocolatey',   stock: 16,  lowStockThreshold: 5,  gradient: 'linear-gradient(145deg,#3d1c08,#6b3a2a)',   accent: '#d4a060', image: 'https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=600&fit=crop&auto=format&q=85', rating: 4.8, reviews: 1432 },
    { id: 26, name: 'Battenberg Cake',          description: 'The iconic Victorian checkerboard cake — pink and yellow almond sponge wrapped in sweet marzipan. A British teatime tradition since 1884.',                                                                price: 4.25,                category: 'Sweets & Cakes', scentType: 'Marzipan & Vanilla',     stock: 14,  lowStockThreshold: 4,  gradient: 'linear-gradient(145deg,#fbcfe8,#fce7f3)',   accent: '#ec4899', image: 'https://images.unsplash.com/photo-1609525313270-e61254f2f0b2?w=600&fit=crop&auto=format&q=85', rating: 4.7, reviews: 765  },
    { id: 27, name: 'Treacle Tart',             description: 'Harry Potter\'s favourite pudding. Golden syrup and fresh breadcrumbs baked in a crisp shortcrust pastry with a classic lattice top. Served warm.',                                                        price: 4.50,                category: 'Sweets & Cakes', scentType: 'Golden & Sticky',        stock: 12,  lowStockThreshold: 4,  gradient: 'linear-gradient(145deg,#fef3c7,#f59e0b)',   accent: '#d97706', image: 'https://images.unsplash.com/photo-1535920527002-b35e96722eb9?w=600&fit=crop&auto=format&q=85', rating: 4.8, reviews: 1098 },
    { id: 28, name: 'Chelsea Bun',              description: 'London\'s very own spiral bun. Soft enriched dough rolled with cinnamon, plump raisins and mixed peel, glazed with sticky golden syrup.',                                                                  price: 3.25,                category: 'Sweets & Cakes', scentType: 'Spiced & Fruity',        stock: 20,  lowStockThreshold: 6,  gradient: 'linear-gradient(145deg,#fde68a,#c8a030)',   accent: '#d97706', image: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc7c?w=600&fit=crop&auto=format&q=85', rating: 4.7, reviews: 876  },
  ])

  const lowStockProducts = computed(() =>
    products.value.filter(p => p.stock > 0 && p.stock <= p.lowStockThreshold)
  )
  const outOfStockProducts = computed(() =>
    products.value.filter(p => p.stock === 0)
  )

  function updateStock(id: number, delta: number) {
    const p = products.value.find(p => p.id === id)
    if (p) p.stock = Math.max(0, p.stock + delta)
  }

  function addProduct(product: Omit<MenuItem, 'id'>) {
    const id = Math.max(0, ...products.value.map(p => p.id)) + 1
    products.value.push({ ...product, id })
  }

  function updateProduct(id: number, updates: Partial<Omit<MenuItem, 'id'>>) {
    const idx = products.value.findIndex(p => p.id === id)
    if (idx !== -1) products.value[idx] = { ...products.value[idx], ...updates }
  }

  function deleteProduct(id: number) {
    products.value = products.value.filter(p => p.id !== id)
  }

  return { products, lowStockProducts, outOfStockProducts, updateStock, addProduct, updateProduct, deleteProduct }
})
